name: sharetext
description: A simple Flutter app to input, save, and receive shared text.
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  receive_sharing_intent: ^1.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
