name: simple_text_saver
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3 # Added shared_preferences
  # 暂时禁用，稍后解决编译问题
  # receive_sharing_intent: ^1.6.9 # Added receive_sharing_intent

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

