name: Build Flutter APK

on:
  push:
    branches:
      - main # Or your default branch
  pull_request:
    branches:
      - main # Or your default branch
  workflow_dispatch:  # 允许手动触发

permissions:
  contents: write  # 允许创建 release 和上传文件
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 获取完整的提交历史

      # 提取提交信息和版本号
      - name: Extract version info
        id: version
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          COMMIT_HASH=$(git rev-parse --short HEAD)
          BUILD_NUMBER=${{ github.run_number }}
          echo "COMMIT_MESSAGE=${COMMIT_MSG}" >> $GITHUB_ENV
          echo "VERSION_NAME=1.0.${BUILD_NUMBER}-${COMMIT_HASH}" >> $GITHUB_ENV

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.29.3'
          cache: true
          
      - name: Accept Android licenses
        run: |
          yes | sdkmanager --licenses
          sdkmanager --version
          
      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            .dart_tool
            .flutter-plugins
            .flutter-plugins-dependencies
            build
          key: flutter-deps-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            flutter-deps-

      - name: Get Flutter dependencies
        run: |
          flutter pub get
          # 显示已安装的依赖版本
          cat pubspec.lock

      - name: Debug Flutter info
        run: |
          flutter doctor -v
          flutter --version
          dart --version

      - name: Analyze Flutter code
        run: flutter analyze || true  # 即使分析失败也继续执行

      - name: Set up Gradle cache
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true

      - name: Fix Android build configuration
        run: |
          # 修复 receive_sharing_intent 插件
          PLUGIN_PATH="$HOME/.pub-cache/hosted/pub.dev/receive_sharing_intent-1.4.5/android/"
          if [ -d "$PLUGIN_PATH" ]; then
            echo 'plugins {' > "$PLUGIN_PATH/build.gradle"
            echo "    id 'com.android.library'" >> "$PLUGIN_PATH/build.gradle"
            echo '}' >> "$PLUGIN_PATH/build.gradle"
            echo '' >> "$PLUGIN_PATH/build.gradle"
            echo 'android {' >> "$PLUGIN_PATH/build.gradle"
            echo '    namespace "com.example.receive_sharing_intent"' >> "$PLUGIN_PATH/build.gradle"
            echo '    compileSdkVersion 33' >> "$PLUGIN_PATH/build.gradle"
            echo '' >> "$PLUGIN_PATH/build.gradle"
            echo '    defaultConfig {' >> "$PLUGIN_PATH/build.gradle"
            echo '        minSdkVersion 16' >> "$PLUGIN_PATH/build.gradle"
            echo '        targetSdkVersion 33' >> "$PLUGIN_PATH/build.gradle"
            echo '    }' >> "$PLUGIN_PATH/build.gradle"
            echo '' >> "$PLUGIN_PATH/build.gradle"
            echo '    compileOptions {' >> "$PLUGIN_PATH/build.gradle"
            echo '        sourceCompatibility JavaVersion.VERSION_1_8' >> "$PLUGIN_PATH/build.gradle"
            echo '        targetCompatibility JavaVersion.VERSION_1_8' >> "$PLUGIN_PATH/build.gradle"
            echo '    }' >> "$PLUGIN_PATH/build.gradle"
            echo '}' >> "$PLUGIN_PATH/build.gradle"
            echo "Fixed receive_sharing_intent plugin build.gradle"
          else
            echo "Plugin directory not found at $PLUGIN_PATH"
            find $HOME/.pub-cache -name "receive_sharing_intent*" -type d
          fi
          
          # 确保本地属性文件存在
          echo "flutter.sdk=$FLUTTER_HOME" > android/local.properties
          
          # 显示环境信息
          echo "FLUTTER_HOME: $FLUTTER_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          ls -la android/

      - name: Build APK
        run: |
          # 显示 Android 构建文件内容以便调试
          echo "Content of android/build.gradle:"
          cat android/build.gradle || echo "File not found"
          
          echo "Content of android/app/build.gradle:"
          cat android/app/build.gradle || echo "File not found"
          
          # 尝试构建
          flutter build apk --release --no-tree-shake-icons

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: success()
        with:
          tag_name: build-${{ github.run_number }}
          name: Build ${{ env.VERSION_NAME }}
          files: build/app/outputs/flutter-apk/app-release.apk
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: true
          body: |
            Automated build from GitHub Actions
            Version: ${{ env.VERSION_NAME }}
            Build Time: ${{ github.event.repository.updated_at }}
            Commit Message: ${{ env.COMMIT_MESSAGE }}

