name: Build and Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'
          channel: 'stable'
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Build APK
        run: flutter build apk --release

      - name: Get version from pubspec
        id: version
        run: |
          VERSION=$(grep 'version:' pubspec.yaml | awk '{print $2}' | tr -d '\r')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          
      - name: Get commit message
        id: commit
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B | tr -d '\n')
          echo "message=$COMMIT_MSG" >> $GITHUB_OUTPUT
          
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: sharetext-${{ steps.version.outputs.version }}-${{ github.run_number }}
          path: build/app/outputs/flutter-apk/app-release.apk
      
      - name: Create Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.version.outputs.version }}+${{ github.run_number }}
          name: Release v${{ steps.version.outputs.version }} Build ${{ github.run_number }}
          body: |
            ${{ steps.commit.outputs.message }}
            
            Automatically built APK from commit ${{ github.sha }}
          files: |
            build/app/outputs/flutter-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 