name: 构建安卓APK

on:
  push:
    branches:
      - main # 或您的默认分支
  pull_request:
    branches:
      - main # 或您的默认分支
  workflow_dispatch:  # 允许手动触发

permissions:
  contents: write  # 允许工作流创建releases和提交文件
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整的提交历史
          
      # 获取最新的 commit message 和版本号信息
      - name: 提取提交信息和版本号
        id: commit_info
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          COMMIT_HASH=$(git rev-parse --short HEAD)
          BUILD_NUMBER=${{ github.run_number }}
          echo "COMMIT_MESSAGE=${COMMIT_MSG}" >> $GITHUB_ENV
          echo "COMMIT_HASH=${COMMIT_HASH}" >> $GITHUB_ENV
          echo "VERSION_NAME=1.0.${BUILD_NUMBER}-${COMMIT_HASH}" >> $GITHUB_ENV
          echo "version_name=1.0.${BUILD_NUMBER}-${COMMIT_HASH}" >> $GITHUB_OUTPUT
          echo "commit_message=${COMMIT_MSG}" >> $GITHUB_OUTPUT

      # 设置Java环境
      - name: 设置Java环境
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
          
      # 输出 Java 环境信息并设置 JAVA_HOME
      - name: 设置 Java 环境变量
        run: |
          echo "Java 版本:"
          java -version
          echo "Java 主目录:"
          echo $JAVA_HOME
          echo "JAVA_HOME=$JAVA_HOME" >> $GITHUB_ENV
          # 创建 local.properties 文件以设置 sdk.dir
          echo "sdk.dir=$ANDROID_HOME" > android/local.properties

      # 设置Flutter环境
      - name: 设置Flutter环境
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # 或您期望的渠道
          flutter-version: '3.29.3' # 可选：指定Flutter版本
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
          cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:'

      # 缓存Flutter依赖
      - name: 缓存Flutter依赖
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            .dart_tool
            .flutter-plugins
            .flutter-plugins-dependencies
            build
          key: flutter-deps-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            flutter-deps-

      - name: 获取Flutter依赖
        run: flutter pub get

      # 构建APK
      - name: 构建APK
        run: flutter build apk --release --no-tree-shake-icons

      # 直接创建GitHub Release而不使用artifacts
      - name: 创建发布并上传APK
        id: create_release
        if: success()
        uses: softprops/action-gh-release@v1
        with:
          tag_name: build-${{ github.run_number }}
          name: 自动构建 ${{ env.VERSION_NAME }}
          files: build/app/outputs/flutter-apk/app-release.apk
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: true
          body: |
            这是GitHub Actions自动构建的APK。
            版本: ${{ env.VERSION_NAME }}
            构建时间: ${{ github.event.repository.updated_at }}
            提交信息: ${{ env.COMMIT_MESSAGE }}

