name: Build Flutter APK

on:
  push:
    branches:
      - main # Or your default branch
  pull_request:
    branches:
      - main # Or your default branch
  workflow_dispatch:  # 允许手动触发

permissions:
  contents: write  # 允许创建 release 和上传文件
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 获取完整的提交历史

      # 提取提交信息和版本号
      - name: Extract version info
        id: version
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          COMMIT_HASH=$(git rev-parse --short HEAD)
          BUILD_NUMBER=${{ github.run_number }}
          echo "COMMIT_MESSAGE=${COMMIT_MSG}" >> $GITHUB_ENV
          echo "VERSION_NAME=1.0.${BUILD_NUMBER}-${COMMIT_HASH}" >> $GITHUB_ENV

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.29.3'
          cache: true
          
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android licenses
        run: |
          echo y | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --list
          
      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            .dart_tool
            .flutter-plugins
            .flutter-plugins-dependencies
            build
          key: flutter-deps-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            flutter-deps-

      - name: Get Flutter dependencies
        run: |
          flutter pub get
          # 显示已安装的依赖版本
          cat pubspec.lock

      - name: Debug Flutter info
        run: |
          flutter doctor -v
          flutter --version
          dart --version

      - name: Analyze Flutter code
        run: flutter analyze || true  # 即使分析失败也继续执行

      - name: Set up Gradle cache
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true

      - name: Fix Android build configuration
        run: |
          # 修复 receive_sharing_intent 插件的 AndroidManifest.xml
          PLUGIN_PATH="$HOME/.pub-cache/hosted/pub.dev/receive_sharing_intent-1.4.5/android"
          MANIFEST_PATH="$PLUGIN_PATH/src/main/AndroidManifest.xml"
          if [ -f "$MANIFEST_PATH" ]; then
            # 备份原文件
            cp "$MANIFEST_PATH" "${MANIFEST_PATH}.bak"
            # 移除 package 属性
            sed -i 's/package="[^"]*"//' "$MANIFEST_PATH"
            echo "Fixed AndroidManifest.xml by removing package attribute"
          fi

          # 修复插件的 build.gradle
          if [ -d "$PLUGIN_PATH" ]; then
            echo 'plugins {' > "$PLUGIN_PATH/build.gradle"
            echo "    id 'com.android.library'" >> "$PLUGIN_PATH/build.gradle"
            echo '}' >> "$PLUGIN_PATH/build.gradle"
            echo '' >> "$PLUGIN_PATH/build.gradle"
            echo 'android {' >> "$PLUGIN_PATH/build.gradle"
            echo '    namespace "com.kasem.receive_sharing_intent"' >> "$PLUGIN_PATH/build.gradle"
            echo '    compileSdkVersion 33' >> "$PLUGIN_PATH/build.gradle"
            echo '' >> "$PLUGIN_PATH/build.gradle"
            echo '    defaultConfig {' >> "$PLUGIN_PATH/build.gradle"
            echo '        minSdkVersion 16' >> "$PLUGIN_PATH/build.gradle"
            echo '        targetSdkVersion 33' >> "$PLUGIN_PATH/build.gradle"
            echo '    }' >> "$PLUGIN_PATH/build.gradle"
            echo '' >> "$PLUGIN_PATH/build.gradle"
            echo '    compileOptions {' >> "$PLUGIN_PATH/build.gradle"
            echo '        sourceCompatibility JavaVersion.VERSION_11' >> "$PLUGIN_PATH/build.gradle"
            echo '        targetCompatibility JavaVersion.VERSION_11' >> "$PLUGIN_PATH/build.gradle"
            echo '    }' >> "$PLUGIN_PATH/build.gradle"
            echo '}' >> "$PLUGIN_PATH/build.gradle"
          fi

          # 修复 NDK 版本问题
          mkdir -p android/app
          {
            echo 'plugins {'
            echo '    id("com.android.application")'
            echo '    kotlin("android")'
            echo '    id("dev.flutter.flutter-gradle-plugin")'
            echo '}'
            echo ''
            echo 'android {'
            echo '    namespace = "com.example.simple_text_saver"'
            echo '    compileSdk = 33'
            echo '    ndkVersion = "27.0.12077973"'
            echo ''
            echo '    defaultConfig {'
            echo '        applicationId = "com.example.simple_text_saver"'
            echo '        minSdk = 16'
            echo '        targetSdk = 33'
            echo '        versionCode = 1'
            echo '        versionName = "1.0"'
            echo '    }'
            echo ''
            echo '    buildTypes {'
            echo '        release {'
            echo '            isMinifyEnabled = false'
            echo '            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")'
            echo '        }'
            echo '    }'
            echo ''
            echo '    compileOptions {'
            echo '        sourceCompatibility = JavaVersion.VERSION_11'
            echo '        targetCompatibility = JavaVersion.VERSION_11'
            echo '    }'
            echo ''
            echo '    kotlinOptions {'
            echo '        jvmTarget = JavaVersion.VERSION_11.toString()'
            echo '    }'
            echo '}'
            echo ''
            echo 'dependencies {'
            echo '    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.6.10")'
            echo '}'
            echo ''
            echo 'flutter {'
            echo '    source = ".."'
            echo '}'
          } > "android/app/build.gradle.kts"
            echo "Fixed receive_sharing_intent plugin build.gradle"
          else
            echo "Plugin directory not found at $PLUGIN_PATH"
            find $HOME/.pub-cache -name "receive_sharing_intent*" -type d
          fi
          
          # 创建项目级别的 build.gradle.kts
          {
            echo 'buildscript {'
            echo '    extra["kotlin_version"] = "1.6.10"'
            echo ''
            echo '    repositories {'
            echo '        google()'
            echo '        mavenCentral()'
            echo '    }'
            echo ''
            echo '    dependencies {'
            echo '        classpath("com.android.tools.build:gradle:7.3.0")'
            echo '        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:${extra[\\"kotlin_version\\"]}")'
            echo '    }'
            echo '}'
            echo ''
            echo 'allprojects {'
            echo '    repositories {'
            echo '        google()'
            echo '        mavenCentral()'
            echo '    }'
            echo '}'
            echo ''
            echo 'tasks.register("clean", Delete::class) {'
            echo '    delete(rootProject.buildDir)'
            echo '}'
          } > "android/build.gradle.kts"

          # 确保本地属性文件存在
          echo "flutter.sdk=$FLUTTER_HOME" > android/local.properties
          echo "sdk.dir=$ANDROID_SDK_ROOT" >> android/local.properties
          
          # 显示环境信息
          echo "FLUTTER_HOME: $FLUTTER_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          echo "ANDROID_SDK_ROOT: $ANDROID_SDK_ROOT"
          ls -la android/

      - name: Build APK
        run: |
          # 显示 Android 构建文件内容以便调试
          echo "Content of android/build.gradle:"
          cat android/build.gradle || echo "File not found"
          
          echo "Content of android/app/build.gradle:"
          cat android/app/build.gradle || echo "File not found"
          
          # 尝试构建
          flutter build apk --release --no-tree-shake-icons

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: success()
        with:
          tag_name: build-${{ github.run_number }}
          name: Build ${{ env.VERSION_NAME }}
          files: build/app/outputs/flutter-apk/app-release.apk
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: true
          body: |
            Automated build from GitHub Actions
            Version: ${{ env.VERSION_NAME }}
            Build Time: ${{ github.event.repository.updated_at }}
            Commit Message: ${{ env.COMMIT_MESSAGE }}

